### ISSUE TITLE
NoMethodError: undefined method `alias_method_chain' ...

### ISSUE THREAD

**Issue by herrfrei** [farend/scm-creator#15]
I tried to install the plugin on Redmine 4.0.0 on a new virtual machine and got this error. Saw that it results from the installed Rails version (5.2.2) and that the method alias_method_chain is used in several files...

**Comment by ishikawa999** [comment]
Thank you for your comment 😄 

Since alias_method_chain is no longer available in Rails 5, the current plugin is no longer working.
For now, I will change the version of Redmine that can use this plugin to 3.4.x only.

**Comment by ishikawa999** [comment]
Someday I may make changes, but the schedule is undecided.

**Comment by ishikawa999** [comment]
I am sorry to have kept you waiting.
This plugin has been modified to work with Redmine 4.0.
You could use it with Redmine 4.0 by acquiring the latest master branch.

⚠️ Note::
Currently, I do not actually use this plugin, so I can not guarantee that this plugin will work in a real environment.
Please contact me at that time as there may be problems that I have not noticed.
